const fs = require('fs');
const path = require('path');

const newDestinations = [
  {
    id: "bhowali",
    name: "Bhowali",
    region: "Kumaon",
    district: "Nainital",
    category: ["Hill Stations"],
    specialty: ["Fruit Orchards", "Scenic"],
    altitude: "1,706 m",
    best_time: ["Spring", "Summer", "Autumn"],
    avoid_time: ["Monsoon"],
    nearest_airport: "Pantnagar Airport",
    nearest_railway: "Kathgodam",
    road_access: "Well connected by road",
    top_attractions: ["Golu Devta Temple", "Fruit Markets"],
    activities: ["Sightseeing", "Shopping"],
    cuisine: ["Kumaoni", "North Indian"],
    stay_types: ["Hotels", "Guesthouses"],
    budget_range: "₹1500 - ₹4000 per day",
    permits_required: ["None"],
    travel_tips: ["Great place to buy local fruits and jams."],
    packing_list: ["Comfortable shoes", "Light jacket"],
    festivals: ["Local fairs"],
    nearby_places: [{ name: "Nainital", id: "nainital" }, { name: "Bhimtal", id: "bhimtal" }],
    image: "/images/destinations/bhowali.jpg",
    description: "A major fruit market and a scenic junction town in the Kumaon hills."
  },
  {
    id: "pangot",
    name: "Pangot",
    region: "Kumaon",
    district: "Nainital",
    category: ["Wildlife / Nature", "Hill Stations"],
    specialty: ["Birdwatching", "Nature"],
    altitude: "1,980 m",
    best_time: ["Spring", "Summer", "Autumn"],
    avoid_time: ["Monsoon"],
    nearest_airport: "Pantnagar Airport",
    nearest_railway: "Kathgodam",
    road_access: "Well connected by road",
    top_attractions: ["Kilbury Bird Sanctuary", "Snow View Point"],
    activities: ["Birdwatching", "Nature Walks", "Photography"],
    cuisine: ["Kumaoni", "North Indian"],
    stay_types: ["Resorts", "Camps"],
    budget_range: "₹2000 - ₹5000 per day",
    permits_required: ["None"],
    travel_tips: ["Carry binoculars for birdwatching."],
    packing_list: ["Binoculars", "Walking shoes", "Warm clothes"],
    festivals: [],
    nearby_places: [{ name: "Nainital", id: "nainital" }],
    image: "/images/destinations/pangot.jpg",
    description: "A small and picturesque hamlet famous for its rich birdlife and dense forests."
  },
  {
    id: "ramnagar",
    name: "Ramnagar",
    region: "Kumaon",
    district: "Nainital",
    category: ["Wildlife / Nature"],
    specialty: ["Gateway to Corbett", "River Kosi"],
    altitude: "345 m",
    best_time: ["Winter", "Spring"],
    avoid_time: ["Monsoon"],
    nearest_airport: "Pantnagar Airport",
    nearest_railway: "Ramnagar",
    road_access: "Well connected by road",
    top_attractions: ["Garjiya Devi Temple", "Kosi River", "Corbett Falls"],
    activities: ["Safari Booking", "Temple Visit"],
    cuisine: ["North Indian", "Kumaoni"],
    stay_types: ["Hotels", "Resorts"],
    budget_range: "₹1500 - ₹5000 per day",
    permits_required: ["Safari permits for Corbett"],
    travel_tips: ["Book safaris well in advance."],
    packing_list: ["Light clothes", "Sunscreen"],
    festivals: ["Karthik Purnima"],
    nearby_places: [{ name: "Jim Corbett", id: "jim-corbett" }, { name: "Kaladhungi", id: "kaladhungi" }],
    image: "/images/destinations/ramnagar.jpg",
    description: "The gateway to Jim Corbett National Park, situated on the banks of the Kosi River."
  },
  {
    id: "kaladhungi",
    name: "Kaladhungi",
    region: "Kumaon",
    district: "Nainital",
    category: ["Heritage / Culture"],
    specialty: ["Jim Corbett Museum", "Nature"],
    altitude: "396 m",
    best_time: ["Winter", "Spring"],
    avoid_time: ["Monsoon"],
    nearest_airport: "Pantnagar Airport",
    nearest_railway: "Haldwani / Ramnagar",
    road_access: "Well connected by road",
    top_attractions: ["Jim Corbett Museum", "Khurpatal"],
    activities: ["Museum Visit", "Nature Walks"],
    cuisine: ["North Indian"],
    stay_types: ["Guesthouses", "Hotels"],
    budget_range: "₹1000 - ₹3000 per day",
    permits_required: ["None"],
    travel_tips: ["Visit the museum to learn about Jim Corbett's life."],
    packing_list: ["Comfortable clothes"],
    festivals: [],
    nearby_places: [{ name: "Nainital", id: "nainital" }, { name: "Ramnagar", id: "ramnagar" }],
    image: "/images/destinations/kaladhungi.jpg",
    description: "A quaint town known for the Jim Corbett Museum, located in his former winter home."
  },
  {
    id: "ranikhet",
    name: "Ranikhet",
    region: "Kumaon",
    district: "Almora",
    category: ["Hill Stations", "Heritage / Culture"],
    specialty: ["Cantonment Town", "Himalayan Views", "Golf Course"],
    altitude: "1,869 m",
    best_time: ["Spring", "Summer", "Autumn"],
    avoid_time: ["Monsoon"],
    nearest_airport: "Pantnagar Airport",
    nearest_railway: "Kathgodam",
    road_access: "Well connected by road",
    top_attractions: ["Chaubatia Gardens", "Jhula Devi Temple", "Upat Golf Course"],
    activities: ["Sightseeing", "Golfing", "Nature Walks"],
    cuisine: ["Kumaoni", "North Indian"],
    stay_types: ["Hotels", "Resorts", "Homestays"],
    budget_range: "₹2000 - ₹6000 per day",
    permits_required: ["None"],
    travel_tips: ["Enjoy the peaceful walks in the cantonment area."],
    packing_list: ["Warm clothes", "Walking shoes"],
    festivals: ["Nanda Devi Mela"],
    nearby_places: [{ name: "Almora", id: "almora" }, { name: "Kausani", id: "kausani" }],
    image: "/images/destinations/ranikhet.jpg",
    description: "A serene cantonment town offering panoramic views of the Himalayas and lush green forests."
  },
  {
    id: "bageshwar",
    name: "Bageshwar",
    region: "Kumaon",
    district: "Bageshwar",
    category: ["Pilgrimage", "Heritage / Culture"],
    specialty: ["Bagnath Temple", "Confluence of Rivers"],
    altitude: "975 m",
    best_time: ["Spring", "Autumn", "Winter"],
    avoid_time: ["Monsoon"],
    nearest_airport: "Pantnagar Airport",
    nearest_railway: "Kathgodam",
    road_access: "Well connected by road",
    top_attractions: ["Bagnath Temple", "Chandika Temple", "Baijnath Temple"],
    activities: ["Temple Visit", "Trekking Base"],
    cuisine: ["Kumaoni"],
    stay_types: ["Hotels", "Guesthouses"],
    budget_range: "₹1000 - ₹3000 per day",
    permits_required: ["None"],
    travel_tips: ["Base for treks like Pindari and Sunderdhunga glaciers."],
    packing_list: ["Modest clothing for temples", "Trekking gear if proceeding further"],
    festivals: ["Uttarayan Mela"],
    nearby_places: [{ name: "Kausani", id: "kausani" }, { name: "Almora", id: "almora" }],
    image: "/images/destinations/bageshwar.jpg",
    description: "A holy city situated at the confluence of Saryu and Gomti rivers, famous for the Bagnath Temple."
  },
  {
    id: "tanakpur",
    name: "Tanakpur",
    region: "Kumaon",
    district: "Champawat",
    category: ["Pilgrimage", "Gateway"],
    specialty: ["Purnagiri Temple", "Sharda River"],
    altitude: "255 m",
    best_time: ["Winter", "Spring"],
    avoid_time: ["Monsoon"],
    nearest_airport: "Pantnagar Airport",
    nearest_railway: "Tanakpur",
    road_access: "Well connected by road",
    top_attractions: ["Purnagiri Temple", "Sharda Ghat", "Banasur Ka Kila"],
    activities: ["Temple Visit", "River Rafting"],
    cuisine: ["North Indian", "Kumaoni"],
    stay_types: ["Hotels", "Dharamshalas"],
    budget_range: "₹1000 - ₹3000 per day",
    permits_required: ["None"],
    travel_tips: ["Expect crowds during the Purnagiri Mela."],
    packing_list: ["Light clothes", "Modest clothing for temples"],
    festivals: ["Purnagiri Mela"],
    nearby_places: [{ name: "Champawat", id: "champawat" }, { name: "Lohaghat", id: "lohaghat" }],
    image: "/images/destinations/tanakpur.jpg",
    description: "A town on the banks of the Sharda River, known as the gateway to the Purnagiri Temple."
  },
  {
    id: "tehri",
    name: "New Tehri",
    region: "Garhwal",
    district: "Tehri Garhwal",
    category: ["Hill Stations", "Lakes and Scenic Retreats"],
    specialty: ["Tehri Dam", "Water Sports"],
    altitude: "1,550 m",
    best_time: ["Spring", "Summer", "Autumn"],
    avoid_time: ["Monsoon"],
    nearest_airport: "Jolly Grant Airport",
    nearest_railway: "Rishikesh",
    road_access: "Well connected by road",
    top_attractions: ["Tehri Dam", "Tehri Lake", "Chandrabadni Temple"],
    activities: ["Boating", "Jet Skiing", "Sightseeing"],
    cuisine: ["Garhwali", "North Indian"],
    stay_types: ["Hotels", "Resorts"],
    budget_range: "₹2000 - ₹6000 per day",
    permits_required: ["None"],
    travel_tips: ["Try the water sports at Tehri Lake."],
    packing_list: ["Comfortable clothes", "Sunscreen"],
    festivals: ["Tehri Lake Festival"],
    nearby_places: [{ name: "Tehri Lake", id: "tehri-lake" }, { name: "Kanatal", id: "kanatal" }],
    image: "/images/destinations/tehri.jpg",
    description: "A modern town built to relocate the residents of Old Tehri, overlooking the massive Tehri Dam."
  },
  {
    id: "govindghat",
    name: "Govindghat",
    region: "Garhwal",
    district: "Chamoli",
    category: ["Pilgrimage", "Trekking"],
    specialty: ["Base Camp", "Confluence"],
    altitude: "1,828 m",
    best_time: ["Summer", "Early Autumn"],
    avoid_time: ["Monsoon", "Winter"],
    nearest_airport: "Jolly Grant Airport",
    nearest_railway: "Rishikesh",
    road_access: "Well connected by road",
    top_attractions: ["Confluence of Alaknanda and Lakshman Ganga"],
    activities: ["Trekking Base", "Pilgrimage"],
    cuisine: ["North Indian", "Punjabi"],
    stay_types: ["Hotels", "Gurudwara"],
    budget_range: "₹1000 - ₹3000 per day",
    permits_required: ["None"],
    travel_tips: ["Starting point for treks to Hemkund Sahib and Valley of Flowers."],
    packing_list: ["Trekking gear", "Warm clothes", "Raincoat"],
    festivals: [],
    nearby_places: [{ name: "Hemkund Sahib", id: "hemkund-sahib" }, { name: "Valley of Flowers", id: "valley-of-flowers" }, { name: "Joshimath", id: "joshimath" }],
    image: "/images/destinations/govindghat.jpg",
    description: "A vital transit hub and base camp for pilgrims and trekkers heading to Hemkund Sahib and the Valley of Flowers."
  },
  {
    id: "mana",
    name: "Mana Village",
    region: "Garhwal",
    district: "Chamoli",
    category: ["Heritage / Culture", "Pilgrimage"],
    specialty: ["Last Indian Village", "Mythology"],
    altitude: "3,200 m",
    best_time: ["Summer", "Early Autumn"],
    avoid_time: ["Winter", "Monsoon"],
    nearest_airport: "Jolly Grant Airport",
    nearest_railway: "Rishikesh",
    road_access: "Well connected by road",
    top_attractions: ["Vyas Gufa", "Ganesh Gufa", "Saraswati River", "Bheem Pul"],
    activities: ["Sightseeing", "Photography"],
    cuisine: ["Local Garhwali", "Maggi/Tea"],
    stay_types: ["Homestays (limited)", "Stay in Badrinath"],
    budget_range: "₹500 - ₹1500 per day",
    permits_required: ["None"],
    travel_tips: ["Visit the 'Last Tea Shop of India'."],
    packing_list: ["Warm clothes", "Comfortable shoes"],
    festivals: [],
    nearby_places: [{ name: "Badrinath", id: "badrinath" }],
    image: "/images/destinations/mana.jpg",
    description: "Known as the last Indian village before the Tibet border, steeped in Mahabharata mythology."
  },
  {
    id: "guptkashi",
    name: "Guptkashi",
    region: "Garhwal",
    district: "Rudraprayag",
    category: ["Pilgrimage"],
    specialty: ["Vishwanath Temple", "Base for Kedarnath"],
    altitude: "1,319 m",
    best_time: ["Summer", "Autumn"],
    avoid_time: ["Monsoon", "Winter"],
    nearest_airport: "Jolly Grant Airport",
    nearest_railway: "Rishikesh",
    road_access: "Well connected by road",
    top_attractions: ["Vishwanath Temple", "Manikarnik Kund", "Ardhanarishwar Temple"],
    activities: ["Temple Visit", "Helicopter Booking"],
    cuisine: ["North Indian", "Garhwali"],
    stay_types: ["Hotels", "Guesthouses"],
    budget_range: "₹1500 - ₹4000 per day",
    permits_required: ["Kedarnath Registration"],
    travel_tips: ["Major hub for booking helicopter rides to Kedarnath."],
    packing_list: ["Modest clothing", "Warm layers"],
    festivals: [],
    nearby_places: [{ name: "Kedarnath", id: "kedarnath" }, { name: "Sonprayag", id: "sonprayag" }, { name: "Ukhimath", id: "ukhimath" }],
    image: "/images/destinations/guptkashi.jpg",
    description: "A significant religious town housing the ancient Vishwanath Temple, serving as a major stopover for Kedarnath pilgrims."
  },
  {
    id: "sonprayag",
    name: "Sonprayag",
    region: "Garhwal",
    district: "Rudraprayag",
    category: ["Pilgrimage"],
    specialty: ["Confluence", "Transit Hub"],
    altitude: "1,829 m",
    best_time: ["Summer", "Autumn"],
    avoid_time: ["Monsoon", "Winter"],
    nearest_airport: "Jolly Grant Airport",
    nearest_railway: "Rishikesh",
    road_access: "Well connected by road",
    top_attractions: ["Confluence of Basuki and Mandakini rivers"],
    activities: ["Pilgrimage Transit"],
    cuisine: ["North Indian"],
    stay_types: ["Hotels", "Dharamshalas"],
    budget_range: "₹1000 - ₹3000 per day",
    permits_required: ["Kedarnath Registration"],
    travel_tips: ["Private vehicles are usually stopped here; pilgrims take shared taxis to Gaurikund."],
    packing_list: ["Warm clothes", "Rain gear"],
    festivals: [],
    nearby_places: [{ name: "Kedarnath", id: "kedarnath" }, { name: "Guptkashi", id: "guptkashi" }],
    image: "/images/destinations/sonprayag.jpg",
    description: "A holy confluence and the main transit point where pilgrims switch to local transport for Gaurikund."
  },
  {
    id: "deoria-tal",
    name: "Deoria Tal",
    region: "Garhwal",
    district: "Rudraprayag",
    category: ["Trekking", "Lakes and Scenic Retreats"],
    specialty: ["Alpine Lake", "Chaukhamba View"],
    altitude: "2,438 m",
    best_time: ["Spring", "Autumn"],
    avoid_time: ["Monsoon"],
    nearest_airport: "Jolly Grant Airport",
    nearest_railway: "Rishikesh",
    road_access: "Trek from Sari Village",
    top_attractions: ["Deoria Tal Lake", "Chaukhamba Peak Views"],
    activities: ["Trekking", "Camping", "Photography"],
    cuisine: ["Local food at Sari village"],
    stay_types: ["Camping", "Homestays in Sari"],
    budget_range: "₹1500 - ₹3000 per day",
    permits_required: ["Forest entry fee"],
    travel_tips: ["An easy 2.5 km trek from Sari village."],
    packing_list: ["Trekking shoes", "Warm clothes", "Camera"],
    festivals: [],
    nearby_places: [{ name: "Chopta", id: "chopta" }, { name: "Ukhimath", id: "ukhimath" }],
    image: "/images/destinations/deoria-tal.jpg",
    description: "A pristine emerald lake offering mesmerizing reflections of the Chaukhamba peaks."
  },
  {
    id: "harsil",
    name: "Harsil",
    region: "Garhwal",
    district: "Uttarkashi",
    category: ["Hill Stations", "Nature"],
    specialty: ["Apple Orchards", "Bhagirathi River", "Scenic"],
    altitude: "2,620 m",
    best_time: ["Summer", "Autumn"],
    avoid_time: ["Monsoon", "Winter"],
    nearest_airport: "Jolly Grant Airport",
    nearest_railway: "Rishikesh",
    road_access: "Well connected by road",
    top_attractions: ["Bhagirathi River", "Dharali", "Mukhba Village"],
    activities: ["Nature Walks", "Sightseeing", "Trekking"],
    cuisine: ["Garhwali", "North Indian"],
    stay_types: ["Hotels", "Homestays"],
    budget_range: "₹2000 - ₹5000 per day",
    permits_required: ["None"],
    travel_tips: ["A perfect, quiet stopover on the way to Gangotri."],
    packing_list: ["Warm clothes", "Walking shoes"],
    festivals: [],
    nearby_places: [{ name: "Gangotri", id: "gangotri" }, { name: "Uttarkashi", id: "uttarkashi" }],
    image: "/images/destinations/harsil.jpg",
    description: "An unspoiled and hidden jewel of Uttarakhand, famous for its apple orchards and the Bhagirathi river."
  },
  {
    id: "uttarkashi",
    name: "Uttarkashi",
    region: "Garhwal",
    district: "Uttarkashi",
    category: ["Pilgrimage", "Adventure"],
    specialty: ["Vishwanath Temple", "Mountaineering"],
    altitude: "1,158 m",
    best_time: ["Spring", "Summer", "Autumn"],
    avoid_time: ["Monsoon", "Winter"],
    nearest_airport: "Jolly Grant Airport",
    nearest_railway: "Rishikesh",
    road_access: "Well connected by road",
    top_attractions: ["Kashi Vishwanath Temple", "Nehru Institute of Mountaineering", "Maneri Dam"],
    activities: ["Temple Visit", "Mountaineering Courses"],
    cuisine: ["Garhwali", "North Indian"],
    stay_types: ["Hotels", "Ashrams"],
    budget_range: "₹1000 - ₹3000 per day",
    permits_required: ["None"],
    travel_tips: ["Known as the 'Kashi of the North'."],
    packing_list: ["Modest clothing", "Comfortable shoes"],
    festivals: ["Magh Mela"],
    nearby_places: [{ name: "Gangotri", id: "gangotri" }, { name: "Harsil", id: "harsil" }],
    image: "/images/destinations/uttarkashi.jpg",
    description: "A holy town on the banks of the Bhagirathi river, home to the famous Vishwanath Temple and NIM."
  },
  {
    id: "barkot",
    name: "Barkot",
    region: "Garhwal",
    district: "Uttarkashi",
    category: ["Pilgrimage", "Hill Stations"],
    specialty: ["Apple Orchards", "Yamunotri Base"],
    altitude: "1,220 m",
    best_time: ["Summer", "Autumn"],
    avoid_time: ["Monsoon", "Winter"],
    nearest_airport: "Jolly Grant Airport",
    nearest_railway: "Dehradun / Rishikesh",
    road_access: "Well connected by road",
    top_attractions: ["Yamuna River", "Apple Orchards"],
    activities: ["Sightseeing", "Transit"],
    cuisine: ["North Indian", "Garhwali"],
    stay_types: ["Hotels", "Camps"],
    budget_range: "₹1500 - ₹4000 per day",
    permits_required: ["None"],
    travel_tips: ["A major stopover for pilgrims heading to Yamunotri."],
    packing_list: ["Warm clothes", "Comfortable shoes"],
    festivals: [],
    nearby_places: [{ name: "Yamunotri", id: "yamunotri" }],
    image: "/images/destinations/barkot.jpg",
    description: "A scenic town offering magnificent views of the Bandarpoonch peak, serving as a base for Yamunotri."
  },
  {
    id: "pauri",
    name: "Pauri",
    region: "Garhwal",
    district: "Pauri Garhwal",
    category: ["Hill Stations", "Heritage / Culture"],
    specialty: ["Himalayan Views", "Temples"],
    altitude: "1,814 m",
    best_time: ["Spring", "Summer", "Autumn"],
    avoid_time: ["Monsoon"],
    nearest_airport: "Jolly Grant Airport",
    nearest_railway: "Kotdwar",
    road_access: "Well connected by road",
    top_attractions: ["Kandoliya Temple", "Chaukhamba Viewpoint", "Kyunkaleshwar Temple"],
    activities: ["Sightseeing", "Nature Walks", "Photography"],
    cuisine: ["Garhwali", "North Indian"],
    stay_types: ["Hotels", "Guesthouses"],
    budget_range: "₹1500 - ₹3500 per day",
    permits_required: ["None"],
    travel_tips: ["Offers some of the widest panoramic views of the Garhwal Himalayas."],
    packing_list: ["Warm clothes", "Camera"],
    festivals: ["Sharad Utsav"],
    nearby_places: [{ name: "Khirsu", id: "khirsu" }, { name: "Srinagar Garhwal", id: "srinagar-garhwal" }],
    image: "/images/destinations/pauri.jpg",
    description: "The district headquarters offering breathtaking, wide-angle views of the snow-capped Himalayan peaks."
  },
  {
    id: "srinagar-garhwal",
    name: "Srinagar Garhwal",
    region: "Garhwal",
    district: "Pauri Garhwal",
    category: ["Heritage / Culture", "Pilgrimage"],
    specialty: ["Education Hub", "Temples", "Alaknanda River"],
    altitude: "560 m",
    best_time: ["Winter", "Spring", "Autumn"],
    avoid_time: ["Monsoon", "Peak Summer"],
    nearest_airport: "Jolly Grant Airport",
    nearest_railway: "Rishikesh",
    road_access: "Well connected by road",
    top_attractions: ["Kamleshwar Mahadev Temple", "Dhari Devi Temple (nearby)", "Alaknanda River"],
    activities: ["Temple Visit", "Sightseeing"],
    cuisine: ["Garhwali", "North Indian"],
    stay_types: ["Hotels", "Guesthouses"],
    budget_range: "₹1000 - ₹3000 per day",
    permits_required: ["None"],
    travel_tips: ["A major educational and cultural center in Garhwal."],
    packing_list: ["Light clothes", "Modest clothing"],
    festivals: ["Baikunth Chaturdashi Mela"],
    nearby_places: [{ name: "Pauri", id: "pauri" }, { name: "Rishikesh", id: "rishikesh" }],
    image: "/images/destinations/srinagar-garhwal.jpg",
    description: "The largest town in the Garhwal Hills, situated on the banks of the Alaknanda River."
  },
  {
    id: "kotdwar",
    name: "Kotdwar",
    region: "Garhwal",
    district: "Pauri Garhwal",
    category: ["Gateway", "Pilgrimage"],
    specialty: ["Gateway to Garhwal", "Sidhbali Temple"],
    altitude: "395 m",
    best_time: ["Winter", "Spring"],
    avoid_time: ["Monsoon"],
    nearest_airport: "Jolly Grant Airport",
    nearest_railway: "Kotdwar",
    road_access: "Well connected by road",
    top_attractions: ["Sidhbali Temple", "Kanvashram", "St. Joseph's Church"],
    activities: ["Temple Visit", "Transit"],
    cuisine: ["North Indian", "Garhwali"],
    stay_types: ["Hotels", "Dharamshalas"],
    budget_range: "₹1000 - ₹3000 per day",
    permits_required: ["None"],
    travel_tips: ["The main entry point for Lansdowne and Pauri."],
    packing_list: ["Light clothes"],
    festivals: [],
    nearby_places: [{ name: "Lansdowne", id: "lansdowne" }],
    image: "/images/destinations/kotdwar.jpg",
    description: "Known as the Gateway to Garhwal, famous for the Sidhbali Hanuman Temple."
  }
];

let destsContent = fs.readFileSync('src/data/destinations.ts', 'utf-8');
const match = destsContent.match(/export const destinations: Destination\[\] = (\[[\s\S]*?\]);/);
const dests = JSON.parse(match[1]);

newDestinations.forEach(nd => {
  if (!dests.find(d => d.id === nd.id)) {
    dests.push(nd);
  }
});

const newContent = destsContent.replace(match[1], JSON.stringify(dests, null, 2));
fs.writeFileSync('src/data/destinations.ts', newContent);
console.log('Added missing destinations to destinations.ts');
